// Mapping product name -> local image path.
export const PRODUCT_IMAGES: Record<string, string> = {
  "Effaclar Gel Moussant Purifiant": "/images/products/la-roche-posay-effaclar-gel-moussant-400ml.jpg",
  "Toleriane Dermo-Nettoyant": "/images/products/la-roche-posay-toleriane-dermo-nettoyant-400ml.jpg",
  "Sensibio H2O Eau Micellaire": "/images/products/bioderma-sensibio-h2o-500ml.jpg",
  "Sébium Gel Moussant": "/images/products/bioderma-sebium-gel-moussant-500ml.jpg",
  "Vinoclean Mousse Nettoyante": "/images/products/caudalie-vinoclean-mousse-nettoyante-150ml.jpg",
  "Hyalu B5 Sérum": "/images/products/la-roche-posay-hyalu-b5-serum-30ml.jpg",
  "Minéral 89 Booster Quotidien": "/images/products/vichy-mineral-89-50ml.jpg",
  "Vinoperfect Sérum Éclat": "/images/products/caudalie-vinoperfect-serum-eclat-30ml.jpg",
  "Pure Vitamin C10 Sérum": "/images/products/la-roche-posay-pure-vitamin-c10-serum-30ml.jpg",
  "Ampoules Concentrées C+": "/images/products/svr-ampoules-concentrees-c-30ml.jpg",
  "NCEF-Reverse Crème Suprême": "/images/products/filorga-ncef-reverse-50ml.jpg",
  "Time-Filler Crème Anti-rides": "/images/products/filorga-time-filler-50ml.jpg",
  "Liftactiv Collagen Specialist": "/images/products/vichy-liftactiv-collagen-specialist-50ml.jpg",
  "Resveratrol-Lift Crème Cachemire": "/images/products/caudalie-resveratrol-lift-creme-cachemire-50ml.jpg",
  "Hydrance Aqua-Gel": "/images/products/avene-hydrance-aqua-gel-50ml.jpg",
  "Toleriane Sensitive Crème": "/images/products/la-roche-posay-toleriane-sensitive-creme-40ml.jpg",
  "Crème Hydratante Visage": "/images/products/cerave-creme-hydratante-visage-52ml.jpg",
  "Crème Prodigieuse Boost Gel-Baume": "/images/products/nuxe-creme-prodigieuse-boost-40ml.jpg",
  "Aquaphor Baume Réparateur": "/images/products/eucerin-aquaphor-baume-reparateur-45ml.jpg",
  "Physiolift Yeux": "/images/products/avene-physiolift-yeux-15ml.jpg",
  "Hyalu B5 Yeux": "/images/products/la-roche-posay-hyalu-b5-yeux-15ml.jpg",
  "Effaclar Duo+ M": "/images/products/la-roche-posay-effaclar-duo-m-40ml.jpg",
  "Sébium Global": "/images/products/bioderma-sebium-global-30ml.jpg",
  "Cleanance Comedomed": "/images/products/avene-cleanance-comedomed-30ml.jpg",
  "Normaderm Phytosolution": "/images/products/vichy-normaderm-phytosolution-50ml.jpg",
  "Sebiaclear Sérum": "/images/products/svr-sebiaclear-serum-30ml.jpg",
  "Lipikar Baume AP+M": "/images/products/la-roche-posay-lipikar-baume-ap-m-400ml.jpg",
  "XeraCalm A.D Crème Relipidante": "/images/products/avene-xeracalm-ad-creme-relipidante-400ml.jpg",
  "Atoderm Intensive Baume": "/images/products/bioderma-atoderm-intensive-baume-500ml.jpg",
  "Huile Prodigieuse": "/images/products/nuxe-huile-prodigieuse-100ml.jpg",
  "Lotion Hydratante Corps": "/images/products/cerave-lotion-hydratante-corps-473ml.jpg",
  "Bariéderm Cica-Crème": "/images/products/uriage-bariederm-cica-creme-100ml.jpg",
  "Lipikar Syndet AP+": "/images/products/la-roche-posay-lipikar-syndet-ap-400ml.jpg",
  "Atoderm Huile de Douche": "/images/products/bioderma-atoderm-huile-de-douche-1l.jpg",
  "Rêve de Miel Gel Douche Ultra-Riche": "/images/products/nuxe-reve-de-miel-gel-douche-400ml.jpg",
  "Crème Mains Cicaplast": "/images/products/la-roche-posay-cicaplast-mains-100ml.jpg",
  "Crème Mains Rêve de Miel": "/images/products/nuxe-creme-mains-reve-de-miel-50ml.jpg",
  "Crème Pieds Réparatrice Urea 10%": "/images/products/eucerin-creme-pieds-urea10-100ml.jpg",
  "Huile Vergetures Bio": "/images/products/mustela-huile-vergetures-bio-105ml.jpg",
  "Shampooing à l'Avoine": "/images/products/klorane-shampooing-avoine-400ml.jpg",
  "Anaphase+ Shampooing": "/images/products/ducray-anaphase-plus-shampooing-400ml.jpg",
  "Dercos Anti-Pelliculaire DS": "/images/products/vichy-dercos-anti-pelliculaire-ds-390ml.jpg",
  "Kelual DS Shampooing": "/images/products/ducray-kelual-ds-shampooing-100ml.jpg",
  "Shampooing au Lait de Papyrus": "/images/products/klorane-shampooing-lait-papyrus-400ml.jpg",
  "Baume Après-Shampooing à la Mangue": "/images/products/klorane-baume-apres-shampooing-mangue-200ml.jpg",
  "Masque Nutri-Réparateur": "/images/products/nuxe-hair-le-masque-nutrition-125ml.jpg",
  "Dercos Aminexil Clinical 5 Femme": "/images/products/vichy-dercos-aminexil-clinical-5-femme.jpg",
  "Neoptide Expert Sérum": "/images/products/ducray-neoptide-expert-serum.jpg",
  "Forcapil Cheveux & Ongles": "/images/products/arkopharma-forcapil-180-gelules.jpg",
  "Sensinol Shampooing Physioprotecteur": "/images/products/ducray-sensinol-shampooing-200ml.jpg",
  "Anthelios UVMune 400 Fluide Invisible SPF50+": "/images/products/la-roche-posay-anthelios-uvmune-400-spf50.jpg",
  "Fotoprotector Fusion Water SPF50": "/images/products/isdin-fotoprotector-fusion-water-spf50-50ml.jpg",
  "Photoderm Nude Touch SPF50+": "/images/products/bioderma-photoderm-nude-touch-spf50-40ml.jpg",
  "Capital Soleil UV-Age Daily SPF50+": "/images/products/vichy-capital-soleil-uv-age-daily-spf50-40ml.jpg",
  "Vinosun Crème Protectrice SPF50": "/images/products/caudalie-vinosun-protect-creme-spf50-50ml.jpg",
  "Anthelios Lait Hydratant SPF50+": "/images/products/la-roche-posay-anthelios-lait-hydratant-spf50-250ml.jpg",
  "Fluide Minéral Corps SPF50+": "/images/products/avene-fluide-mineral-corps-spf50-100ml.jpg",
  "Photoderm Spray SPF50+": "/images/products/bioderma-photoderm-spray-spf50.jpg",
  "Posthelios Gel-Crème Après-Soleil": "/images/products/la-roche-posay-posthelios-apres-soleil-200ml.jpg",
  "Lait Après-Soleil Réparateur": "/images/products/avene-lait-apres-soleil-reparateur-200ml.jpg",
  "Anthelios Dermo-Pediatrics Lait SPF50+": "/images/products/la-roche-posay-anthelios-dermo-pediatrics-250ml.jpg",
  "Pediatrics Fusion Water SPF50": "/images/products/isdin-pediatrics-fusion-water-spf50-50ml.jpg",
  "Gel Lavant Doux": "/images/products/mustela-gel-lavant-doux-500ml.jpg",
  "Eau Nettoyante Sans Rinçage": "/images/products/mustela-eau-nettoyante-sans-rincage-300ml.jpg",
  "ABCDerm Moussant": "/images/products/bioderma-abcderm-moussant-1l.jpg",
  "Crème Change 1-2-3": "/images/products/mustela-creme-change-1-2-3-100ml.jpg",
  "Cicalfate+ Crème Réparatrice": "/images/products/avene-cicalfate-plus-creme-reparatrice-100ml.jpg",
  "Baume Corps Maternité": "/images/products/mustela-baume-corps-maternite-200ml.jpg",
  "Arkovital Pure Energy": "/images/products/arkopharma-arkovital-pure-energy-30-comprimes.jpg",
  "Vitamine D3 2000 UI": "/images/products/arkopharma-vitamine-d3-2000-ui-60-capsules.jpg",
  "Arkogélules Ginseng Bio": "/images/products/arkopharma-arkogelules-ginseng-bio-45-gelules.jpg",
  "Arkorelax Sommeil Fort 8h": "/images/products/arkopharma-arkorelax-sommeil-fort-8h.jpg",
  "Arkogélules Magnésium Marin": "/images/products/arkopharma-arkogelules-magnesium-marin-60-gelules.jpg",
  "Skin Booster Collagène": "/images/products/filorga-skin-booster-collagene-30-sticks.jpg",
  "Arkogélules Charbon Végétal": "/images/products/arkopharma-arkogelules-charbon-vegetal-45-gelules.jpg",
  "Dentifrice Sensibilité": "/images/products/eucerin-dentifrice-sensibilite-75ml.jpg",
  "Gyn-Phy Gel Intime": "/images/products/uriage-gyn-phy-gel-intime-500ml.jpg",
  "Déodorant 48h Anti-Traces": "/images/products/vichy-deodorant-48h-anti-traces-50ml.jpg",
  "Déodorant Roll-on Douceur": "/images/products/avene-deodorant-roll-on-douceur-50ml.jpg",
  "Cicaplast Baume B5+": "/images/products/la-roche-posay-cicaplast-baume-b5-100ml.jpg",
  "Bariéderm Cica Spray": "/images/products/uriage-bariederm-cica-spray-100ml.jpg",
};
